Created place and distance microservices
rogowski-piotr/system-benchmarking-monolith-vs-microservices pull request #5
Opened 2022-07-11 19:28 UTC by EquablePanic4

Created two independent microservices - place and distance. Change design pattern.

2022-07-12 11:09 UTC, rogowski-piotr requested changes

2022-07-12 11:18 UTC, EquablePanic4 commented on .NET/.dockerignore
> +**/.classpath
Good point - this file doesn't do anything in that place. It should be moved to project's directories.

2022-07-13 20:01 UTC, rogowski-piotr requested changes
We added e2e tests please update your branch and uncomment [these](https://github.com/rogowski-piotr/system-benchmarking-monolith-vs-microservices/blob/8ab583c8efe8d2252659e3864936e20bb68cac98/.github/workflows/test.yml#L88) lines to test your changes 😉

2022-07-14 15:41 UTC, EquablePanic4 commented on .NET/Microservices/DistanceService/DistanceService.csproj.user
> +    <ActiveDebugProfile>Docker</ActiveDebugProfile>
This is just Visual Studio file

2022-07-14 15:43 UTC, EquablePanic4 commented on .NET/Microservices/PlaceService/Program.cs
> +//Get all places
Yes, there is possibility to make separate controllers

2022-07-14 15:43 UTC, EquablePanic4 commented on .NET/SystemBenchmarkingMonolithVsMicroservices.sln
> +﻿
Yes, we really need this file, it's Visual Studio Solution file.

2022-07-14 15:44 UTC, EquablePanic4 commented on .NET/Microservices/DistanceService/Requests/DistanceRequest.cs
> +        public List<Point> GetPoints()
Yes, it is.

2022-07-14 15:44 UTC, EquablePanic4 commented on .NET/Microservices/DistanceService/Program.cs
> +    return Results.Ok(new DistanceResponse(distance));
No problem

2022-07-14 15:44 UTC, EquablePanic4 commented on .NET/Microservices/DistanceService/Services/SphericalDistanceService.cs
> +        //public double CalculateDistance(double lat1, double long1, double lat2, double long2)
You're right

2022-07-14 15:46 UTC, EquablePanic4 commented on .NET/Microservices/PlaceService/Models/Place.cs
> +        [JsonPropertyName("id")]
[JsonPropertyName] is an attribute which makes Json Serializer use exactly that name while serializing or deserializing objects

2022-07-16 14:19 UTC, rogowski-piotr approved these changes
Good Job 🥇 Thanks!

2022-07-16 14:30 UTC, merged